### ISSUE TITLE
Cuda out of memory when running main_texture_transfer.py

### ISSUE THREAD

**Issue by Sibylle-Van-Hove** [halfjoe/3D-Portrait-Stylization#6]
After successfully running the Face Reconstruction & deformation I'm encountering the following error when running the Texture Stylization step (transfer/main_texture_transfer.py) on the provided test data (00016):

```
Traceback (most recent call last):
  File "./transfer/main_texture_transfer.py", line 199, in <module>
    run(dir_data_sub)
  File "./transfer/main_texture_transfer.py", line 127, in run
    images = renderer_model(azi=azi[aov_id], ele=ele[aov_id])
  File "/home/gpu/anaconda3/envs/3d-portrait-stylization/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gpu/avatarTech/3D-Portrait-Stylization/texture_style_transfer/transfer/model_ortho_RE.py", line 61, in forward
    elevation=self.elevation, azimuth=self.azimuth, show_forehead=True)
  File "/home/gpu/avatarTech/3D-Portrait-Stylization/texture_style_transfer/neural_renderer/renderer.py", line 185, in render_rgb
    textures = torch.cat((textures, textures.permute((0, 1, 4, 3, 2, 5))), dim=1)
RuntimeError: CUDA out of memory. Tried to allocate 1.36 GiB (GPU 0; 15.90 GiB total capacity; 14.49 GiB already allocated; 869.44 MiB free; 64.90 MiB cached)

```

What are the GPU requirements to run transfer/main_texture_transfer.py?

**Comment by cutegao715** [comment]
could you please offer me the .bin file provided in the repository, this is unavailable now.
